[package]
name = "a62_a53_a44_integrated_prototype"
version = "0.1.0"
edition = "2021"
autobins = false

[features]
default = []
diagnostic-trace = []

[dependencies]
tfhe = { version = "=1.7.0", features = ["integer"] }
rayon = "1"
bincode = "1"
dyn-stack = "0.13"
aligned-vec = "0.6"
sha2 = "0.10"

[profile.release]
opt-level = 3

[[bin]]
name = "a160_first_ks_prefix"
path = "src/main.rs"
required-features = ["diagnostic-trace"]
